language: generic
sudo: required
services:
        - docker

before_install:
        - docker build -t sreejith1/react-test -f ./client/Dockerfile.dev ./client

script:
        - docker run -e CI=true sreejith1/react-test npm test

after_success:
        - docker build -t sreejith1/complex-client ./client
        - docker build -t sreejith1/complex-nginx ./nginx
        - docker build -t sreejith1/complex-server ./server
        - docker build -t sreejith1/complex-worker ./worker

        - echo "$DOCKER_PASSWORD" | docker login -u "DOCKER_ID" --password-stdin

        - docker push sreejith1/complex-client
        - docker push sreejith1/complex-nginx
        - docker push sreejith1/complex-server
        - docker push sreejith1/complex-worker

deploy:
        edge: true
        provider: elasticbeanstack
        region: us-east-1
        app: multi-docker
        env: MultiDocker-env
        bucket_name: elasticbeanstalk-us-east-1-123456789012
        bucket_path: docker-multi
        on:
                branch: release
        access_key_id: $AWS_ACCESS_KEY
        secret_access_key: $AWS_SECRET_KEY
